### ISSUE TITLE
Build in FeenICS pipeline

### ISSUE THREAD

**Issue by jerdra** [TIGRLab/TIGR_PURR#14]
Processing of spiral scans requires special treatment in that in order for scans to be usable at all they must be processed using FeenICS. 

@edickie and I have discussed auto-running FeenICS on any spiral data and outputting directly into the BIDS data directory (essentially over-writing the un-corrected spirals). 

We will probably need a separate nextflow pipeline to handle this, or alternatively, design a BIDS-app that we can run through the master script (bids.nf).

**Comment by edickie** [comment]
I don't think we should overwrite the bids spiral input data...maybe
dm_to_bids needs to not be exporting un-corrected spirals??

**Comment by jerdra** [comment]
Yeah this is a difficult issue to deal with... I don't like the idea of dm_to_bids implementing this functionality solely because it's already a mess, and hardcoding additional functionally for archival reasons (for old data of a type we'll never collect again) will make maintenance annoying moving forward.

The FeenICS solution of overwriting BIDS outputs also isn't elegant as we'd have to continually deal with this weirdness instead of having a uniform interface to work with. 

A possible solution could be to correct the spirals, and re-zip them for XNAT upload. We'd have to archive the old zips for data-management sake but we would not longer have to treat spiral scans as a special case. (This can also be applied to re-orienting scans as well).

If we want to maintain old spirals (not oriented and/or uncorrected) in data/nii we could make a tag for them for keeping the data but ignore that tag in the new version of dm_to_bids via config

Of course the easiest outcome would be to have fmriprep supports derivatives as inputs...

Thoughts @edickie @DESm1th @josephmje, @gabiherman ?

**Comment by jerdra** [comment]
pipeline built in to output into <PROJ>/pipelines/. 
Currently working on a process to deal with orientation issues automatically.

**Comment by jerdra** [comment]
finished this awhile ago :speak_no_evil:
